"""adds foreign key to task model

Revision ID: 597eae61227e
Revises: d1add1f87cbf
Create Date: 2024-11-07 21:32:14.628030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597eae61227e'
down_revision = 'd1add1f87cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
